# Borra la línea 'version: 3.8' (obsoleta)

services:
  #--- SERVICIO 1: EL BACKEND ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Inyecta la URL de la BD desde el archivo /.env
      DATABASE_URL: ${DATABASE_URL}

  #--- SERVICIO 2: EL FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: # <-- ¡ESTA ES LA SECCIÓN NUEVA/CLAVE!
        # Le pasamos la URL del backend LOCAL al Dockerfile
        VITE_API_URL_ARG: http://localhost:3000/api
    restart: always
    ports:
      - "80:80"
    # La variable 'environment' aquí no es necesaria
    # porque la "horneamos" durante el build con 'args'.