[build]
builder = "nixpacks"
buildCommand = "npm ci --prefix frontend && npm run build --prefix frontend"

[deploy]
startCommand = "npm run start --prefix frontend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10